name: tests

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]
    steps:
      - uses: actions/checkout@v6
      - run: rustup toolchain install ${{ matrix.rust }} --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: rustfmt checks
        run: cargo fmt --check
      - name: clippy lints
        run: cargo clippy
      - name: unit tests
        run: cargo test
